version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      APP_URL: http://yoururl.com
      API_KEY: 'your-secrey-api-key'
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DB: shortenlink
